export type Prefecture =
  | 'HOKKAIDO'
  | 'AOMORI'
  | 'IWATE'
  | 'MIYAGI'
  | 'AKITA'
  | 'YAMAGATA'
  | 'FUKUSIMA'
  | 'IBARAKI'
  | 'TOCHIGI'
  | 'GUNMA'
  | 'SAITAMA'
  | 'CHIBA'
  | 'TOKYO'
  | 'KANAGAWA'
  | 'NIGATA'
  | 'TOYAMA'
  | 'ISHIKAWA'
  | 'HUKUI'
  | 'YAMANASHI'
  | 'NAGANO'
  | 'GIFU'
  | 'SHIZUOKA'
  | 'AICHI'
  | 'MIE'
  | 'SHIGA'
  | 'KYOTO'
  | 'OSAKA'
  | 'HYOGO'
  | 'NARA'
  | 'WAKAYAMA'
  | 'TOTTORI'
  | 'SHIMANE'
  | 'OKAYAMA'
  | 'HIROSHIMA'
  | 'YAMAGUCHI'
  | 'TOKUSHIMA'
  | 'KAGAWA'
  | 'EHIME'
  | 'KOUCHI'
  | 'HUKUOKA'
  | 'SHAGA'
  | 'NAGASAKI'
  | 'KUMAMOTO'
  | 'OITA'
  | 'MIYAZAKI'
  | 'KAGOSHIMA'
  | 'OKINAWA';
export const PREFECTURES_JA: Record<Prefecture, string> = {
  HOKKAIDO: '北海道',
  AOMORI: '青森',
  IWATE: '岩手',
  MIYAGI: '宮城',
  AKITA: '秋田',
  YAMAGATA: '山形',
  FUKUSIMA: '福島',
  IBARAKI: '茨城',
  TOCHIGI: '栃木',
  GUNMA: '群馬',
  SAITAMA: '埼玉',
  CHIBA: '千葉',
  TOKYO: '東京',
  KANAGAWA: '神奈川',
  NIGATA: '新潟',
  TOYAMA: '富山',
  ISHIKAWA: '石川',
  HUKUI: '福井',
  YAMANASHI: '山梨',
  NAGANO: '長野',
  GIFU: '岐阜',
  SHIZUOKA: '静岡',
  AICHI: '愛知',
  MIE: '三重',
  SHIGA: '滋賀',
  KYOTO: '京都',
  OSAKA: '大阪',
  HYOGO: '兵庫',
  NARA: '奈良',
  WAKAYAMA: '和歌山',
  TOTTORI: '鳥取',
  SHIMANE: '島根',
  OKAYAMA: '岡山',
  HIROSHIMA: '広島',
  YAMAGUCHI: '山口',
  TOKUSHIMA: '徳島',
  KAGAWA: '香川',
  EHIME: '愛媛',
  KOUCHI: '高知',
  HUKUOKA: '福岡',
  SHAGA: '佐賀',
  NAGASAKI: '長崎',
  KUMAMOTO: '熊本',
  OITA: '大分',
  MIYAZAKI: '宮崎',
  KAGOSHIMA: '鹿児島',
  OKINAWA: '沖縄',
} as const;

export const PREFECTURES_EN: Record<Prefecture, string> = {
  HOKKAIDO: 'HOKKAIDO',
  AOMORI: 'AOMORI',
  IWATE: 'IWATE',
  MIYAGI: 'MIYAGI',
  AKITA: 'AKITA',
  YAMAGATA: 'YAMAGATA',
  FUKUSIMA: 'FUKUSIMA',
  IBARAKI: 'IBARAKI',
  TOCHIGI: 'TOCHIGI',
  GUNMA: 'GUNMA',
  SAITAMA: 'SAITAMA',
  CHIBA: 'CHIBA',
  TOKYO: 'TOKYO',
  KANAGAWA: 'KANAGAWA',
  NIGATA: 'NIGATA',
  TOYAMA: 'TOYAMA',
  ISHIKAWA: 'ISHIKAWA',
  HUKUI: 'HUKUI',
  YAMANASHI: 'YAMANASHI',
  NAGANO: 'NAGANO',
  GIFU: 'GIFU',
  SHIZUOKA: 'SHIZUOKA',
  AICHI: 'AICHI',
  MIE: 'MIE',
  SHIGA: 'SHIGA',
  KYOTO: 'KYOTO',
  OSAKA: 'OSAKA',
  HYOGO: 'HYOGO',
  NARA: 'NARA',
  WAKAYAMA: 'WAKAYAMA',
  TOTTORI: 'TOTTORI',
  SHIMANE: 'SHIMANE',
  OKAYAMA: 'OKAYAMA',
  HIROSHIMA: 'HIROSHIMA',
  YAMAGUCHI: 'YAMAGUCHI',
  TOKUSHIMA: 'TOKUSHIMA',
  KAGAWA: 'KAGAWA',
  EHIME: 'EHIME',
  KOUCHI: 'KOUCHI',
  HUKUOKA: 'HUKUOKA',
  SHAGA: 'SHAGA',
  NAGASAKI: 'NAGASAKI',
  KUMAMOTO: 'KUMAMOTO',
  OITA: 'OITA',
  MIYAZAKI: 'MIYAZAKI',
  KAGOSHIMA: 'KAGOSHIMA',
  OKINAWA: 'OKINAWA',
} as const;
